/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as FeeEstimatorRouteImport } from './routes/fee-estimator'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportAgentRouteImport } from './routes/support-agent'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeEstimatorRoute = FeeEstimatorRouteImport.update({
  id: '/fee-estimator',
  path: '/fee-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportAgentRoute = SupportAgentRouteImport.update({
  id: '/support-agent',
  path: '/support-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/engagements': typeof EngagementsRoute
  '/fee-estimator': typeof FeeEstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/support-agent': typeof SupportAgentRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/engagements': typeof EngagementsRoute
  '/fee-estimator': typeof FeeEstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/support-agent': typeof SupportAgentRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/engagements': typeof EngagementsRoute
  '/fee-estimator': typeof FeeEstimatorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/support-agent': typeof SupportAgentRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/clients'
    | '/compliance'
    | '/documents'
    | '/engagements'
    | '/fee-estimator'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/settings'
    | '/support-agent'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/clients'
    | '/compliance'
    | '/documents'
    | '/engagements'
    | '/fee-estimator'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/settings'
    | '/support-agent'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/clients'
    | '/compliance'
    | '/documents'
    | '/engagements'
    | '/fee-estimator'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/settings'
    | '/support-agent'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ClientsRoute: typeof ClientsRoute
  ComplianceRoute: typeof ComplianceRoute
  DocumentsRoute: typeof DocumentsRoute
  EngagementsRoute: typeof EngagementsRoute
  FeeEstimatorRoute: typeof FeeEstimatorRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SupportAgentRoute: typeof SupportAgentRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-estimator': {
      id: '/fee-estimator'
      path: '/fee-estimator'
      fullPath: '/fee-estimator'
      preLoaderRoute: typeof FeeEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-agent': {
      id: '/support-agent'
      path: '/support-agent'
      fullPath: '/support-agent'
      preLoaderRoute: typeof SupportAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ClientsRoute: ClientsRoute,
  ComplianceRoute: ComplianceRoute,
  DocumentsRoute: DocumentsRoute,
  EngagementsRoute: EngagementsRoute,
  FeeEstimatorRoute: FeeEstimatorRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SupportAgentRoute: SupportAgentRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
